// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlW1f3JWCr_LCCDtDKJ6eVNNAANbjINxs',
    appId: '1:338431764486:web:e43ea495c0e2de86fdbb87',
    messagingSenderId: '338431764486',
    projectId: 'aviator-delivery',
    authDomain: 'aviator-delivery.firebaseapp.com',
    databaseURL:
        'https://aviator-delivery-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aviator-delivery.appspot.com',
    measurementId: 'G-RW0H6C15JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFn0gJGUcbwKzWXRqHFINVKcaST_M1FJU',
    appId: '1:338431764486:android:b878e1e007af23d9fdbb87',
    messagingSenderId: '338431764486',
    projectId: 'aviator-delivery',
    databaseURL:
        'https://aviator-delivery-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aviator-delivery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKreEg1bZXFa2Gk54uM8R6OiKI_s7-Aww',
    appId: '1:338431764486:ios:853a6aa5dc8556abfdbb87',
    messagingSenderId: '338431764486',
    projectId: 'aviator-delivery',
    databaseURL:
        'https://aviator-delivery-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aviator-delivery.appspot.com',
    iosBundleId: 'com.example.aviatorDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKreEg1bZXFa2Gk54uM8R6OiKI_s7-Aww',
    appId: '1:338431764486:ios:4be9b4d0f243e377fdbb87',
    messagingSenderId: '338431764486',
    projectId: 'aviator-delivery',
    databaseURL:
        'https://aviator-delivery-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aviator-delivery.appspot.com',
    iosBundleId: 'com.example.aviatorDelivery.RunnerTests',
  );
}
